### ISSUE TITLE
Missing type line information "A"

### ISSUE THREAD

**Issue by HugoPrototypo** [byte-foundry/spectral.ptf#2]
![capture d ecran 2018-07-17 a 15 39 12](https://user-images.githubusercontent.com/37330805/42820901-94ed16bc-89d7-11e8-9652-7cdb39f390bf.png)

This stem should always be a line

**Comment by yannickmathey** [comment]
#fixed with ad93a1cd28a650ea9dda3827de3bbe447ddc89dc
